[package]
name = "rspymod"
version = "0.1.0"
authors = ["Swarnim Arun <swarnimarun11@gmail.com>"]
edition = "2018"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]
